Add mean and covariance to the MvNormal variations
TuringLang/DistributionsAD.jl pull request #120
Opened 2020-10-13 20:27 UTC by jlperla

2020-10-13 20:39 UTC, devmotion requested changes
Thanks! I left some comments and suggestions.

The latest version of Requires breaks the tests. It would be good to merge the fixes in https://github.com/TuringLang/DistributionsAD.jl/pull/119 first, to make sure that tests actually pass in this PR.

2020-10-13 20:39 UTC, devmotion commented on Project.toml
> +Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
`Statistics.mean` and `Statistics.cov` are already available since we load Distributions:
```suggestion
```

2020-10-13 20:39 UTC, devmotion commented on src/DistributionsAD.jl
> +import Statistics: mean, cov
IMO it is better, or rather more readable, to not import overloaded methods:
```suggestion
```

2020-10-13 20:39 UTC, devmotion commented on src/multivariate.jl
> +cov(d::TuringDenseMvNormal) = Array(d.C)  # turns cholesky to matrix
```suggestion
# Mean and covariance
Distributions.mean(d::TuringDiagMvNormal) = d.m
Distributions.mean(d::TuringScalMvNormal) = d.m
Distributions.mean(d::TuringDenseMvNormal) = d.m
Distributions.cov(d::TuringDiagMvNormal) = Diagonal(abs2.(d.σ))
Distributions.cov(d::TuringScalMvNormal) = Diagonal(Fill(abs2(d.σ),length(d.m)))
Distributions.cov(d::TuringDenseMvNormal) = Array(d.C)  # turns cholesky to matrix
```

2020-10-13 20:40 UTC, jlperla commented
Are you able to take this over and fix it to your hearts content?  These things are gettingb above my git paygrade

2020-10-13 20:43 UTC, theogf commented on test/others.jl
> +        C = A * A' + I
It would be nice to have testing for a larger category of matrices.

2020-10-13 20:52 UTC, devmotion commented
> Are you able to take this over and fix it to your hearts content? These things are gettingb above my git paygrade

I applied the suggestions (one can just commit them in Github's webinterface, next to the comment with the suggestion). There's some minor issue with ReverseDiff and Skellam in the linked PR (which contains the fixes for the CI). I haven't merged it yet since I am waiting for @mohamed82008's suggestions on how to fix this problem. Let's see if it will be fixed within the next few days - otherwise I'll extract the CI fixes and merge them in a separate PR.

2020-10-13 20:55 UTC, jlperla commented
Thanks so much!

2020-10-20 09:12 UTC, nmheim commented
while we are at it, would it be ok to also add the `var` methods? :)

2021-01-10 14:07 UTC, devmotion commented
It seems there was some problem with merging master.

2021-01-10 14:12 UTC, jlperla commented
@devmotion  I tried to rebase to see if the CI is working now, but my gitfoo is weak.  This might be something you can more efficiently do.  Hope that I didn't mess things up.  If you completely drop this PR and just redo your change to a new one I wouldn't be offended.  Sorry if I made things worse.

2021-01-10 14:29 UTC, devmotion commented
No worries, I'll have a look and fix the git issues. I'm sorry, somehow I forgot this PR.

2021-01-10 14:32 UTC, jlperla commented
No apologies at all, you are doing so much.  Sorry I couldn't be more useful.

If you do decide to throw this out and restart (and it is a trivial addition), maybe add in the variance that @nmheim  suggested?

2021-01-10 14:36 UTC, devmotion commented
> maybe add in the variance that @nmheim suggested?

I agree, we should add it regardless of how the git issues are resolved :slightly_smiling_face:

2021-01-10 15:43 UTC, devmotion reviewed
Looks good to me now, but since I got involved and added some commits someone else should approve the PR.

2021-01-10 16:36 UTC, torfjelde approved these changes
Am happy!

2021-01-10 22:45 UTC, merged

2021-01-10 22:45 UTC, devmotion commented
Thanks a lot @jlperla!